#ifndef __StateMachineMyFrame__
#define __StateMachineMyFrame__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "stateMachine.h"

//// end generated include

/** Implementing MyFrame1 */
class StateMachineMyFrame : public MyFrame1
{
	public:
		/** Constructor */
		StateMachineMyFrame( wxWindow* parent );
	//// end generated class members
	
};

#endif // __StateMachineMyFrame__
