#ifndef __UIMyFrame1__
#define __UIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "freeUI.h"

//// end generated include

/** Implementing MyFrame1 */
class UIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void ugv_mode( wxCommandEvent& event );
		void walk_mode( wxCommandEvent& event );
		void stair_mode( wxCommandEvent& event );
		void table_mode( wxCommandEvent& event );
	public:
		/** Constructor */
		UIMyFrame1( wxWindow* parent );
	//// end generated class members
	
};

#endif // __UIMyFrame1__
